version: "3.7"

services:
  timescaledb:
    image: timescale/timescaledb:latest
    container_name: timescaledb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      -   grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
    restart: always
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - /home/pi_bamford/mqtt/config:/mosquitto/config

volumes:
  timescaledb-data:
  grafana-data:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-config: